stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

build:
  stage: build
  image: docker:latest
  script:
    - export TAG=`if [ "$CI_COMMIT_REF_NAME" == "master" ]; then echo "latest"; else echo $CI_COMMIT_REF_NAME ; fi`
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$TAG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$TAG