# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 965a216985a9a57042222845d030cfbdd96bfc4083c65a2a2521d053e28e6562336b2da1691399c31eec89de040c07a5112180667e77fe9d3f3e5c326a036c8e

test:
  secret_key_base: ca35d5397c23df61e539c8aef71b486d505312b606659100fcc29dcbb29077444ec4af303a5830e7bc0248f327490bde6b9da91f7b4f253fee760eca2a7e66ab

staging:
  secret_key_base: 965a216985a9a57042222845d030cfbdd96bfc4083c65a2a2521d053e28e6562336b2da1691399c31eec89de040c07a5112180667e77fe9d3f3e5c326a036c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
